//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang_EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDon
    {
        public int Id { get; set; }
        public int DonHangId { get; set; }
        public int MonAnId { get; set; }
        public byte SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
