//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang_EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int Id { get; set; }
        public int DonHangId { get; set; }
        public decimal TongTien { get; set; }
        public decimal TienGiam { get; set; }
        public decimal TienThanhToan { get; set; }
        public string PhuongThuc { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
